<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Actividad extends Model
{
    protected $fillable = [
        'dia',
        'horario',
        'animal_id',
    ];

    public function animal()
    {
        return $this->belongsTo('App\Models\Animal', 'animal_id');
    }
}
