<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'nombre',
        'edad',
        'genero',
    ];

    public function actividads()
    {
        return $this->hasMany('App\Models\Actividad');
    }
}
